version: '2'
services:
    lab:
        build: .
        environment:
            - DATABASE_CLIENT=pg
            - DATABASE_HOST=database
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=password
            - DATABASE_USERNAME=username
            - DATABASE_DATABASE=lab
            - DEBUG=knex:tx
        links:
            - postgres:database
        volumes:
            - .:/opt/lab
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=username
            - POSTGRES_DB=lab